### ISSUE TITLE
Building image for raspberry pi zero 2 w - Fails to boot

### ISSUE THREAD

**Issue by luisimasd** [jakues/zerowrt#8]
Executed the script to build the image
Tested:
openwrt-19.07.10-zerowrt-brcm2708-bcm2709-rpi-2-ext4-factory.img.gz < LED off, no booting up
openwrt-19.07.10-zerowrt-brcm2708-bcm2710-rpi-3-ext4-factory.img.gz < LED off, no booting up
openwrt-22.03.2-zerowrt-bcm27xx-bcm2710-rpi-3-ext4-factory.img.gz < LED on, no booting up
openwrt-22.03.2-zerowrt-bcm27xx-bcm2709-rpi-2-ext4-factory.img.gz< LED on, no booting up

Any idea about how to make it boot on the raspberry pi zero 2 w?

SDCard build with Raspberry imager v.1.7.3

**Comment by savioruz** [comment]
Hi! thanks for submitting issue. Currently openwrt doesn't support raspi zero 2W because of firmware license. That firmware basicly use imagebuilder in order to speed up build. I need try [this method](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=e9f9cd14cc71826957877999fd063dd080de4751) coz no official imagebuilder that have support pi zero 2W.

**Comment by luisimasd** [comment]
I understand that the method noted there is just for the wifi module, am i wrong?
